# Generated by Django 5.1.6 on 2025-02-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('fileid', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('eventid', models.BigIntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('isVectorized', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'filestore',
            },
        ),
    ]
